# Generated by Django 3.1.3 on 2020-11-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageApp_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='reciever',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.EmailField(max_length=255),
        ),
    ]
