# Generated by Django 3.1.3 on 2020-11-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageApp_api', '0002_auto_20201106_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
