# Generated by Django 3.0 on 2021-02-13 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('admin', '0004_auto_20210213_1831'),
        ('messageApp_api', '0004_auto_20210213_1829'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
